### ISSUE TITLE
Doesn’t seem to detect M600 pause

### ISSUE THREAD

**Issue by ssrjazz** [fraschetti/Octoslack#12]
Was hoping to use this to detect when an M600 (marlin fw) was issued to pause the print and change filament. Is this possible or can only detect octoprint events only?

**Comment by fraschetti** [comment]
G-code based events are currently under development. Stay tuned.

**Comment by fraschetti** [comment]
1.4.0 has been released and includes support for G-code events

**Comment by ssrjazz** [comment]
THANK YOU!   1.4.0 works GREAT for this!  This will make some of my prints so much easier to catch when its time to switch filament!
