### ISSUE TITLE
Riot.im renamed to Element

### ISSUE THREAD

**Issue by natrius** [fraschetti/Octoslack#132]
I guess most people know this anyway, but i think it should be renamed everywhere from Riot to Element. New link, just in case https://element.io/

**Comment by fraschetti** [comment]
Changes committed for the next release. I'll go ahead and close this ahead of that as there's not really much else to test or worry about here. Thanks for opening this issue!

**Comment by natrius** [comment]
Thanks for your work! 

If i recall correctly, when ur doing a push or merge in git and write something along the lines of "Closing #132" it should autoclose the issue once its merged - if i understood everything correctly. Might be usefull to try.
