### ISSUE TITLE
suggestion: timed status when not printing

### ISSUE THREAD

**Issue by uwezi** [fraschetti/Octoslack#25]
I would appreciate if there was an option to send regular status messages from the bot even when the printer is not printing - just to see that everything is ok...

**Comment by fraschetti** [comment]
Thanks for the suggestion, I'll add it to the list.

**Comment by fraschetti** [comment]
Hi @uwezi 
This logic is in and it'll be included in the next update.
Keep an eye out for a new "Printer status heartbeat" event which can be configured to send a message every N minutes

**Comment by fraschetti** [comment]
This functionality is now available in 1.6.0

Curently the heartbeat is active even when printing. Let me know if that's an annoyance I can consider halting the heartbeats while a print is in progress.
