### ISSUE TITLE
Version number in Setup.py is wrong

### ISSUE THREAD

**Issue by trunzoc** [fraschetti/Octoslack#35]
Setup.py still says 1.6.0.  Octoprint keeps showing the update notification, because even though 1.6.1 is installed, it thinks is 1.6.0

**Comment by fraschetti** [comment]
Thanks @trunzoc 
I've just bumped the version to 1.6.1 and published a "new" release. Once OctoPrint's internal plugin cache expires (should be less than 24 hours) or if you fore an upgrade check, you should see 1.6.2 and be good to go after that upgrade.

Thanks for letting me know about this issue.

**Comment by trunzoc** [comment]
Thanks!
