### ISSUE TITLE
[Feature Request] Limit what commands can be executed & access controls

### ISSUE THREAD

**Issue by smitty97** [fraschetti/Octoslack#52]
I need a separate "listen to commands" toggle that only allows safe readonly commands.  So my slack buddies don't mess with prints.  :) Or, have it do stop/pause/resume only from a specified slack username.

**Comment by tedder** [comment]
What commands would be remaining in this use case?

**Comment by smitty97** [comment]
i suppose just 'status'

**Comment by tedder** [comment]
It doesn't seem terribly worthwhile- just unset it and adjust the progress percentage to the right level.

**Comment by smitty97** [comment]
Yeah, you have a point.  I'd like it to be useful though, just not open to abuse from all in that channel.  How about the allowed username list?

**Comment by fraschetti** [comment]
A duplicate request - https://github.com/fraschetti/Octoslack/issues/56#issue-459986188

**Comment by fraschetti** [comment]
Hi @smitty97 @tedder @Mortikhan

I've finished development on this item and it'll be included in the next Octoslack release (TBD but not far off).

What I added:
-Individual commands can be enabled/disabled completely via the Octoslack config UI
-Individual commands can be marked as 'Restricted' which if combined with a list of authorized users (this can also be supplied via the Octoslack UI), will reject commands from any unauthorized users.

I'll comment here again once the new release has gone out. In the mean time, feel free to ask any questions you might have.

**Comment by Mortikhan** [comment]
Excellent news. Can't wait for the new version to come out. Thanks a ton!

**Comment by fraschetti** [comment]
@smitty97 @tedder @Mortikhan 

This functionality has been relased in Octoslack 1.9.0. Feel free to provide any feedback you might have.

**Comment by Mortikhan** [comment]
Works very well. Thanks for the update and new functionality.
