### ISSUE TITLE
Rotate additional Camera

### ISSUE THREAD

**Issue by djfab59** [fraschetti/Octoslack#53]
Hello,

First, thanks for this plugin.

Is there a way to rotate an additional camera?

**Comment by fraschetti** [comment]
Hi @djfab59 

Not yet but this should be a simple addition; the only cost is the extra CPU/time to rotate the image(s).
I'll take a look when time permits.. stay tuned.

**Comment by fraschetti** [comment]
Good news @djfab59 ...

I found a bit of time tonight to add this into Octoslack. I have a few other changes I'd like to implement soon and once those other tasks are complete, this functionality will be available.

**Comment by fraschetti** [comment]
Hi @djfab59 
This functionality is now included in the 1.8.0 release.
Please let me know if you run into any issues.
