### ISSUE TITLE
Updated to 1.8.0, settings not being saved or shown properly

### ISSUE THREAD

**Issue by kazibole** [fraschetti/Octoslack#55]
Upgraded from 1.7.2 to 1.8.0. I noticed that my custom gcode events were no longer working. Checked the settings page and they were gone. I can re-create them but when I restart OctoPrint they will be lost again. I also noticed that some of the other settings are behaving strangely.

ETA timestamp time zone is blank: 
![image](https://user-images.githubusercontent.com/34734155/59718972-e90a9f00-91e0-11e9-894a-dd7b70e18f44.png)

Snapshot hosting is also blank (it should be "Slack"): 
![image](https://user-images.githubusercontent.com/34734155/59719006-fe7fc900-91e0-11e9-84c8-bf9d87cbeb21.png)

If I choose "Slack" and restart OctoPrint, it will be blank again.

**Comment by fraschetti** [comment]
Hi @kazibole 

I've identified and fixed the issue - you may need to resave your settings once you upgrade.

I've just pushed 1.8.1 - feel free to give it a try and let me know whether or not I've resolved your issue.

Thanks in advamce.

**Comment by kazibole** [comment]
Appears to be fixed in 1.8.1!
