### ISSUE TITLE
Option to change the Print progress {pct_complete} by variables  of % or H:M and add new +1 channel for private pings 

### ISSUE THREAD

**Issue by Ballzyk0umpa** [fraschetti/Octoslack#6]
1) Since Octoslack is pinging a printer status every 10% intervals There should be a need to modify that to at least 25% OR have it ping it to a private channel within MatterMost. Might wanna add a second option in your plugin under the category "Slack Identity" for a  2nd (or more) Channel name.

2) Maybe add a drop down option to change the Print progress {pct_complete} by variables of either % or H:M (and a given interval). Example: Printer pings Octoslack at 25% OR 30min intervals the status of the current print

**Comment by fraschetti** [comment]
1.20 has been published and should address both 1 and 2 above.

-The % interval for reporting print progress is now configurable
-For print progress reporting, you can use the existing % based interval as well as a new time (minutes) based interval (you can even use both if you like)
-I haven't yet found time to look into proper direct message support but for now all messages can now be sent to one or more channels and at the individual event level (e.g. Print progress), events can be configured to send to only specific channels as needed.
