### ISSUE TITLE
WebDAV image upload

### ISSUE THREAD

**Issue by oblivian** [fraschetti/Octoslack#64]
Hey,

Thanks for a super great plugin. Would you concider adding support for WebDAV posting/upload of images? Hence a general agnostic image upload function. Most if not all cloud services support WebDAV, and would make it easier to integrate, be it OneDrive, Dropbox, Nextcloud or any other self-hosted web server, etc.

Thanks.

**Comment by calonmerc** [comment]
Duplicate of #37

**Comment by fraschetti** [comment]
Closing as duplicate.
