### ISSUE TITLE
Request Discord Webhook integration

### ISSUE THREAD

**Issue by JohnOCFII** [fraschetti/Octoslack#72]
Hi Chris,

Our 3D Printing Community on Mattermost is moving to Discord.  I was wondering if you'd be able to integrate a web hook to send OctoSlack output to Discord?  It seems like similar web hook support exists in Discord: https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

Here is the new Discord: https://discord.gg/QGVbBT

Thanks,

John

**Comment by fraschetti** [comment]
Hi John,

I have been slacking on adding discord support; looks like it's finally time.
Do you mind sending me an e-mal (fraschetti.dev@gmail.com) with a new invite? I'll try to catch it before it expires this time. 

Thanks!

**Comment by fraschetti** [comment]
Work in progress...

**Comment by fraschetti** [comment]
Supported added in 1.9.5 - let me know if you encounter any issues.
