### ISSUE TITLE
Not uploading timelapses to Slack

### ISSUE THREAD

**Issue by calonmerc** [fraschetti/Octoslack#77]
For a while now, all of my Octoprint images have been unable to upload timelapses to Slack. The timelapse rendering completes, I get a notification about it, but there's no URL for it. I've double checked my settings and it is supposed to include the URL.

The big problem is that the local timelapses get removed.

**Comment by fraschetti** [comment]
Hi @calonmerc 

Do you mind providing some rough details about your environment?
-What device/OS are you running?
-How are you connecting to Slack (Webhook or API token)?
-Do you mind following the steps below to generate a debug log for analysis?

1. Enable DEBUG logging
2. Reproduce the issue
3. Send Octoprint.log

Instructions to enable DEBUG logging for Octoslack

* Enable DEBUG logging
Ensure the following has been added to /home/pi/.octoprint/logging.yaml  (or appropriate path for your OctoPrint installation)
```
loggers:
  octoprint.plugins.Octoslack:
    level: DEBUG
```

* Restart OctoPrint
```
sudo service octoprint restart
```

For OctoPi releases, the log file will be located in:
/home/pi/.octoprint/logs/octoprint.log

**Comment by calonmerc** [comment]
-What device/OS are you running?
--Variety of Pi 3B and 3B+, all running Raspbian from the OctoPi image.
-How are you connecting to Slack (Webhook or API token)?
--Using the API token on all of them. (The same token, if it matters)
-Do you mind following the steps below to generate a debug log for analysis?
-- I will do these after this print finishes.

**Comment by calonmerc** [comment]
[octoprint.log](https://github.com/fraschetti/Octoslack/files/4457831/octoprint.log)

**Comment by chrisfraschetti** [comment]
Thanks @calonmerc 

It would appear we have ourselves a typo specific to using Slack as the image/video hosting provider. I'm working on a few other changes and I'll fix/test/commit this as time permits.

Question - was this working before (hosting everything via Slack directory) or did you recently switch from something like S3 to Slack?

Thanks again for the debug log.

**Comment by calonmerc** [comment]
Probably a year and a half ago I was using imgur or something, but I've been using Slack, with the timelapse uploads, for consistently over a year. I stopped printing much in November, started again at the end of February. That's when I noticed the timelapses weren't showing anymore.

**Comment by fraschetti** [comment]
Hi @calonmerc 

I likely broke the Slack asset upload as part of _recent_ release. There were a number of scenarios where the code might try to use an old upload method if the user was swapping around configurations. The logic to ensure the setup was correct for Slack uploads had a typo.
I've submitted a fix which will be included in my next release.

**Comment by calonmerc** [comment]
Awesome! Any ETA on the release? Or any help running dev code? (I don't see a development branch to pull)

**Comment by fraschetti** [comment]
Hi @calonmerc 
Shouldn't be long before I push a new release - likely within the next week or so.
As far as the dev branch is concerned, this project has been fairly simple thus far and I haven't needed to break out a dev branch from the main branch.  If you want to test the change, you can simply pull the main branch and go from there. If you haven't seen this page before, the steps to register a development plugin can be found here - https://docs.octoprint.org/en/master/plugins/gettingstarted.html

**Comment by brad-colbert** [comment]
May I "pile on" this thread?

I'm not seeing either snapshots or timelapses posted to Slack.  I'm assuming that Octoslack is able to post both directly?  If not I apologize for not understanding.

Cheers!

**Comment by fraschetti** [comment]
Hi @calonmerc 
I've pushed new Octoslack 2.0.0 release which should address your Slack upload issue. Give it a try - if you still experience issues, feel free to reopen this ticket.

**Comment by fraschetti** [comment]
Hi @brad-colbert 

Assuming you're config is also setup to use Slack to host the snapshots/timelapses, the new release should fix your issue as well. It you were using a different hosting method or are experiencing a different issue, feel free to open another ticket that we can use to investigate your issue further.

**Comment by brad-colbert** [comment]
Yep, testing now.  Will know in roughly 3.5 hours!   Thank you for all of
your hard work!  Fantastic plugin!

Kind regards,
Brad
