### ISSUE TITLE
Octoslack Not Listening

### ISSUE THREAD

**Issue by Llama-Trauma** [fraschetti/Octoslack#84]
After configuring the App, Slack is successfully sending automated print messages; however, none of the commands sent back through slack are triggering a response. 

I have "Listen for commands" and "Use Slack identity" checked. 'Help' and 'Status' do not respond. 
![Slack Capture](https://user-images.githubusercontent.com/32855921/80740176-89ea0c00-8acc-11ea-94e2-bf47d5ffe551.PNG)

My Slack names are all over the place, but the only 'Active' App I see in Slack for mentions is MK2.
![Slack App Settings](https://user-images.githubusercontent.com/32855921/80740524-0d0b6200-8acd-11ea-8850-7924938547fa.PNG)

Also curious why I only see "Print started: {print_name}, Estimate: {remaining_time}" under Fallback? If I want to remove the 'User' from the print started dialogue, is there a way to customize this further?
![Octoslack Settings Capture](https://user-images.githubusercontent.com/32855921/80739914-219b2a80-8acc-11ea-8b85-2fefc74fc486.PNG)

Thank you for your support!

**Comment by Humsie** [comment]
i struggled with the same problem last week, and also found a lot of RTM login failures in the log file.
Turns out octoslack uses the "old" rtm api which requires a "classic" slack bot. 

i created a classic bot using the link from: https://api.slack.com/rtm#classic
and used the "Bot User OAuth Access Token" in octoslack and status command worked. (and the failures stopped in the log file :))

**Comment by fraschetti** [comment]
Hi @Llama-Trauma and @Humsie 

@Humsie is indeed correct - Octoslack currently leverages the older/classic bot support within Slack which supports RTM (websockets). Unfortunately the new Slack bots/apps are a bit different (for good reason) but unfortunately RTM is no longer supported for new bots.
For now, I'd rely on the workaround @Humsie listed above but I am currently working on adding proper support for the bot/app connectivity requirements. 

Stay tuned.

**Comment by fraschetti** [comment]
Hi @Llama-Trauma and @Humsie 

I've just released Octoslack 2.0.0 which includes proper support for the new Slack Apps/Bots.  This includes new logic to move away from the RTM functionality only available to classic Slack Apps/Bots.

What scopes/permissions you need will depend on what you want to do with the plugin. I've included the list of scopes within the plugin settings dialog but I'll also share them here for initial reference. This list may change over time as Slack makes changes or as we add additional functionality to the plugin. The Octoslack settings dialog should be see as the source of truth going forward.

### **Slack Bot Webhook Scopes**
Bot Token Scopes requied for posting to a channel
- channels:read
- chat:write
- groups:read

Bot Token Scopes requied for uploading assets/files to Slack
- files:write


### **Slack Bot Access Token Scopes**

Bot Token Scopes requied for posting to a channel
- channels:read
- chat:write
- groups:read

Bot Token Scopes requied for uploading assets/files to Slack
- files:write

Bot Token Scopes requied for listening for and responding to commands
- channels:history
- groups:history
- reactions:write
- users:read

**Comment by Llama-Trauma** [comment]
Thanks for the update, Chris! 

Would you be able to direct me towards a guide for setting up the Slackbot side of this plugin? I am able to receive automated print notifications still, but I cannot get any of the live Slackbot commands to work for checking status, or affecting the print.
