### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by duczen** [fraschetti/Octoslack#91]
Octoprint 1.4.0 is compatible with python 3. Please consider supporting this as python 2 is now eol.

**Comment by tedder** [comment]
Is this something you can help with, @duczen?

**Comment by fraschetti** [comment]
FYI - 

The current dev version I'm testing in preparation for a release is 100% Python 3 compatible.

**Comment by fraschetti** [comment]
I've released Octoslack 2.0.0 which has full Python 3 support. Give it a try under Python 3 and let me know if you run into any issues.
